# Generated by Django 5.1.1 on 2024-09-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('incomplete', 'Incomplete')], max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Taskdetail',
        ),
    ]
